import os
print("Python Alpha CMD")
print('Введите "help сmd" для помощи по терминалу.')
while True:
    command = input('>>> ')
    if command == "compilation":
        path_input = input("Путь к файлу: ")
        path_output = input("Путь к готовому файлу: ")
        file_input = open(path_input, encoding='utf-8', mode='r')
        text = file_input.read()
        text = text.replace("-число-", "int")
        text = text.replace("-строка-", "str")
        text = text.replace("-дробь-", "float")
        text = text.replace("-лог-", "bool")
        text = text.replace("-правда-", "True")
        text = text.replace("-ложь-", "False")
        text = text.replace("-ничего-", "None")
        text = text.replace("-вывод-", "print")
        text = text.replace("-ввод-", "input")
        text = text.replace("-функция-", "def")
        text = text.replace("-вернуть-", "return")
        text = text.replace("-класс-", "class")
        text = text.replace("-использовать-", "import")
        text = text.replace("-и-", "and")
        text = text.replace("-или-", "or")
        text = text.replace("-в-", "in")
        text = text.replace("-не-", "not")
        text = text.replace("-является-", "is")
        text = text.replace("-если-", "if")
        text = text.replace("-иначе_если-", "elif")
        text = text.replace("-иначе-", "else")
        text = text.replace("-попробовать-", "try")
        text = text.replace("-исключить-", "except")
        text = text.replace("-когда-", "while")
        text = text.replace("-для-", "for")
        text = text.replace("-диапазон-", "range")
        text = text.replace("-прервать-", "break")
        text = text.replace("-выйти-", "quit")
        text = text.replace("-общедоступность-", "global")
        text = text.replace("-пропустить-", "pass")
        text = text.replace("-двоичная-", "bin")
        text = text.replace("-восьмеричная-", "oct")
        text = text.replace("-десятичная-", "dec")
        text = text.replace("-шестнадцатеричная-", "hex")
        text = text.replace("-с-", "with")
        text = text.replace("-как-", "as")
        text = text.replace("-из-", "from")
        file_output = open(path_output, encoding="utf-8", mode="w+")
        file_output.write(text)
        file_output.close()
        print("Компиляция завершена. Файл доступен по указанному пути.")
        ans = input("Запустить файл? (y/n): ")
        if ans == "y":
            os.startfile(path_output)
    elif command == "version":
        print("1.1\n")

    elif command == "about":
        print("Python Alpha - Язык пhограммирования, основанный на Python. Использует кирилические символы и русские слова. Синтаксис схож с Python.\n")

    elif command == "help cmd":
        print('"about" - о ЯП')
        print('"compilation" - скомпилировать программу')
        print('"version" - версия ЯП')
        print('"help cmd" - помощь по терминалу')
        print('"help keyword" - помощь по ЯП')
        print('"exit" - выйти из терминала\n')

    elif command == "help keyword":
        print('-число- -строка- -дробь- -лог-')
        print('-правда- -ложь- -ничего-')
        print('-функция- -вернуть- -класс- -использовать-')
        print('-и- -или- -в- -не-')
        print('-если- -иначе_если- -иначе- -попробовать-')
        print('-исключить- -когда- -для- -диапозон-')
        print('-прервать- -выйти- -общедоступность- -пропустить-')
        print('-двоичная- -восьмеричная- -десятичная- -шестнадцатеричная-')
        print("-пропустить- -вывод - -ввод- -является-")
        print("-c- -как- -из-\n")

    elif command == "exit":
        quit()